name: Default pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run lint
      - run: npm run build

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #     - run: npm ci
  #     - run: npm run build

  #     - name: Test ssh connection
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: whoami

  #     - name: Upload files content via scp
  #       uses: appleboy/scp-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         source: ./dist/*
  #         target: /var/www/test.hammap.io/public_html
  #         rm: true

  #     - name: Move files from dist to public_html
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd /var/www/test.hammap.io/public_html/dist/
  #           mv * ..
  #           rm -rf /var/www/test.hammap.io/public_html/dist/

  #     # - name: npm install
  #     #   uses: appleboy/ssh-action@master
  #     #   with:
  #     #     host: ${{ secrets.SSH_HOST }}
  #     #     username: ${{ secrets.SSH_USER }}
  #     #     key: ${{ secrets.SSH_PRIVATE_KEY }}
  #     #     script: |
  #     #       cd /var/www/test.hammap.io/public_html/
  #     #       npm install
